### ISSUE TITLE
Ability to copy out a list of recipients

### ISSUE THREAD

**Issue by Avelous** [BuidlGuidl/Eth-Splitter#16]
A good feauture to have is a button somewhere that lets you copy the list of recipients filled or/and export it as a text file.

![recipients](https://github.com/BuidlGuidl/Eth-Splitter/assets/86206128/b63f7db2-3889-4faa-910a-2f5539ada282)

**Comment by Avelous** [comment]
This will be tricky, but It would also be nice to be able to have some kind of url you can send around that repopulates a split to these addresses. The url would also update as someone else adds a new valid addresses so if someone copy pastes they get the filled in split

**Comment by ZakGriffith** [comment]
This would be a great feature!  An example use case of this, when we are filling cohort streams ie. sanctum, ENS, balancer, etc...  I end up copying and pasting all the addresses in.  If I had a bookmark with all the cohorts listed, then I could just remove any that don't need funding and split the Eth much quicker.
