### ISSUE TITLE
Branch new-ui - Landing page

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/Eth-Splitter#18]
When landing on the new-ui branch page before you have connected a wallet, the page appears bare and doesn't lead to user to what they need to do next.  A Landing page with a quick description of what the site does, along with a 'connect wallet' button would go a long way to guide the user experience to what we're going for.

**Comment by electrone901** [comment]
i can help

**Comment by ZakGriffith** [comment]
@electrone901 Excellent!  A think a link to the contract code on Etherscan would be helpful too for transparency.  

Had this theme in mind for the landing page, but with our own stuff
https://hackedwalletrecovery.com/

**Comment by electrone901** [comment]
Sounds good, do you have the link to the contract code on Etherscan?

**Comment by ZakGriffith** [comment]
I think this one has kinda been scrapped over time, closing.
