### ISSUE TITLE
Copy/Pasteable URL with populated list of addresses

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/Eth-Splitter#38]
As per @Avelous:

_This will be tricky, but It would also be nice to be able to have some kind of url you can send around that repopulates a split to these addresses. The url would also update as someone else adds a new valid addresses so if someone copy pastes they get the filled in split_

**Comment by austintgriffith** [comment]
i want this one🙏🙏🙏 being able to send around a split using the url would be amazing 

if you make a change and it auto populates the url so you can just copy from the url bar 

(but also there is some share link that one click copies too plz)
