### ISSUE TITLE
When splitting tokens, add some preloaded options

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/Eth-Splitter#9]
When splitting tokens, it take time to find the token address and enter it.  Let's give them some options to choose as default and have those token addresses already loaded.  Some examples I can think of would be

Ethereum DAI: 0x6B175474E89094C44Da98b954EedeAC495271d0F
OP Token: 0x4200000000000000000000000000000000000042
ENS Token: 0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72
Ethereum USDC: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

Not sure the best way to implement these preexisting tokens, possibly a drop down, or we could even add the token Logos to click with an "Other" option to enter a token address.

A consideration here is what network we are on.  If they choose to split OP Tokens, it will need to switch over to Optimism.  Most of these other tokens exist on multiple chains so the user will just have to pay attention to what the network is.

**Comment by electrone901** [comment]
I can work on this

**Comment by ZakGriffith** [comment]
Looks like this is closed in the latest PR
